### ISSUE TITLE
No list created

### ISSUE THREAD

**Issue by landru29** [commonsguy/cwac-anddown#10]
I have the following markdown: "- item1 \n- item2" or  "\* item1 \n\* item2"
It should be converted to:

<ul>
<li>item1</li>
<li>item2</li>
</ul>

but the text remains unchanged

**Comment by commonsguy** [comment]
I am just passing the string to `hoedown`. `hoedown` apparently is not recognizing your markup. Try adding a newline at the end of the string (e.g., `"- item1 \n- item2\n"`) and see if that helps.

**Comment by landru29** [comment]
No. Not better. Here is my test in my android program:
> public void test() {
>   &nbsp;&nbsp;      com.commonsware.cwac.anddown.AndDown processor = new com.commonsware.cwac.anddown.AndDown();
>   &nbsp;&nbsp;      Log.i("Markdown", processor.markdownToHtml("Hello world:\n* one\n* two\n* three\n"));
>     }

And here is what I get:
> &lt;p&gt;Hello world:
>    \* one
>    \* two
>    \* three&lt;/p&gt;

(the same result if I use minus instead of star)

**Comment by commonsguy** [comment]
Your problem, if there is one, is with `hoedown`, as the **`hoedown`** command gives the same output for your input. `"Hello world:\n\n* one\n* two\n* three\n"` gives you a bulleted list.

**Comment by ruckus** [comment]
I'm seeing the exact same issue. I've also tried the MarkdownJ library and it doesn't render lists as well, neither does **hoedown** on the command line. But whats strange is that if you take the same markdown and paste it into a GitHub comment box (this one!) then it gets rendered with the correct HTML lists. 

My first thought is the input markdown is invalid and GitHub has just a better/lenient processor.

```bash
$ echo "Hello world:\n* one\n* two\n* three\n" | hoedown
<p>Hello world:\n* one\n* two\n* three\n</p>
```

:(

**Comment by commonsguy** [comment]
Closing as nothing that I can really do anything about.
