### ISSUE TITLE
Publish v0.2.3 to repo.commonsware.com

### ISSUE THREAD

**Issue by vickychijwani** [commonsguy/cwac-anddown#11]
Hi there,

Thanks for this project! If you have some time, could you please publish v0.2.3 to https://repo.commonsware.com.s3.amazonaws.com/? The latest version available there is v0.2.2, which apparently uses a very old version of hoedown.

PS: Thanks for your extensive contributions to the Android community!

**Comment by commonsguy** [comment]
My apologies for the delay in responding -- I was out of the office.

Further apologies for screwing this up. I thought that I had published the artifact when I was working on the 0.2.3 tag, but apparently I had not. It is out there now.

**Comment by vickychijwani** [comment]
No problem at all. Thanks!
