### ISSUE TITLE
Consider 64bit release

### ISSUE THREAD

**Issue by rshah** [commonsguy/cwac-anddown#12]
In nexus9 it failed to load the library.
Got this error:
/vendor/lib64, /system/lib64 couldn't find "libanddown.so"

Please consider providing 64bit release of this library.

**Comment by commonsguy** [comment]
I just pushed v0.2.4 that adds 64-bit support (x86 and ARM). Note that you may need to use `--refresh-dependencies` to get Gradle to pick up the new AAR for the next 24 hours or so.

**Comment by rshah** [comment]
Thank you, it works.
