### ISSUE TITLE
Could you please enable HOEDOWN_EXT_NO_INTRA_EMPHASIS

### ISSUE THREAD

**Issue by rshah** [commonsguy/cwac-anddown#13]
I have problem rendering url which contain underscore.

When i enabled HOEDOWN_EXT_NO_INTRA_EMPHASIS the url below rendered correctly

> quote with link: https://www.addtoany.com/buttons/customize/floating_share_buttons

But if not
https://www.addtoany.com/buttons/customize/floatingsharebuttons

Which 'share' will be changed to italic

**Comment by commonsguy** [comment]
Addressed in v0.3.0 -- you can now pass in extensions and flags.
