### ISSUE TITLE
Math Equation

### ISSUE THREAD

**Issue by mafcm** [commonsguy/cwac-anddown#15]
Hi,

Please, does cwac-anddown take in account Mathematic equation ?

**Comment by commonsguy** [comment]
Please read the project documentation to learn [where to ask questions](https://github.com/commonsguy/cwac-anddown#questions).

This project is simply a wrapper around [hoedown](https://github.com/hoedown/hoedown). It only does whatever hoedown does in terms of Markdown conversion. This library presently uses hoedown 3.0.1, and [reportedly hoedown has MathJax support](https://github.com/hoedown/hoedown/pull/114). I have never tried it and I do not know if I would need to modify this library to enable hoedown MathJax support.

If you find that command-line hoedown supports MathJax, but this library does not, comment back on this issue with the Markdown/MathJax code that does not work, and I can look into enabling MathJax support.
