### ISSUE TITLE
Nested quotes, new lines behavior

### ISSUE THREAD

**Issue by ferrandp** [commonsguy/cwac-anddown#18]
Hello,

I tried to convert a java string:
```
>**Text1**\n>Text2\n
```
and got as a result:
```
<blockquote>\n<p><strong>Text1</strong>\nText2</p>\n</blockquote>\n
```
whereas I would have expected something like:
```
<blockquote><p><strong>Text1</strong><br/>Text2</p></blockquote>
```
or:
```
<blockquote>\n<p><strong>Text1</strong><br/>\nText2</p>\n</blockquote>\n
```

The problem here concerns both "`\n`" and "`<br/>`". Is this the expected behavior ?
Thanks in advance.

**Comment by commonsguy** [comment]
If you are having a problem with the Markdown->HTML conversion, that is an issue with [hoedown](https://github.com/hoedown/hoedown), the C library that CWAC-AndDown wraps. You would have to take it up with the hoedown developers.
