### ISSUE TITLE
Broken on some v7.1.1 devices?

### ISSUE THREAD

**Issue by contrapunctus-1** [commonsguy/cwac-anddown#19]
Please see
https://github.com/gsantner/markor/issues/9

**Comment by commonsguy** [comment]
Per [the contribution guidelines](https://github.com/commonsguy/cwac-anddown/blob/master/CONTRIBUTING.md#contributing-bug-reports), please provide me with the code and steps necessary to reproduce the problem.

**Comment by contrapunctus-1** [comment]
@commonsguy I'm merely an affected end-user and have no experience or knowledge of programming for Android. I have listed the steps in the linked issue.

**Comment by commonsguy** [comment]
Closing as not reproducible. After all, you claim to encounter your problem with [Octodroid](https://github.com/slapperwan/gh4a), which does not use this library.
