### ISSUE TITLE
Strikethrough markdown not parsing.

### ISSUE THREAD

**Issue by MrVadi** [commonsguy/cwac-anddown#20]
Hello. trying to parse text like "\~\~Random text\~\~" and it's not converting it to Html \<s> or \<strike> - so I cannot get "~~Random text~~".

Using it like:
`AndDown andDown = new AndDown()`
`andDown.markdownToHtml("~~random text~~")`

Unfortunately didn't find any documentation about it.

**Comment by commonsguy** [comment]
Try `markdownToHtml("~~random text~~", AndDown.HOEDOWN_EXT_STRIKETHROUGH, 0)`
