### ISSUE TITLE
Gradle not sync

### ISSUE THREAD

**Issue by salman-hameed-brainx** [commonsguy/cwac-anddown#24]
Could not HEAD 'https://dl.bintray.com/petrovkristiyan/maven/com/commonsware/cwac/anddown/0.4.0/anddown-0.4.0.pom'. Received status code 502 from server: Bad Gateway

I'm using this library for 1year but I'm getting this issue from yesterday.

Note:
1- I'm not using any proxy
2- I've internet
3- I removed this library project builds successfully.

**Comment by commonsguy** [comment]
That is not my artifact &mdash; I have never hosted anything in Bintray.

Details are in [the project README](https://github.com/commonsguy/cwac-anddown#installation) for how to use my artifact.
