### ISSUE TITLE
Consider new hoedown API capabilities

### ISSUE THREAD

**Issue by commonsguy** [commonsguy/cwac-anddown#9]
hoedown 3 supports various flags; consider exposing them in the AndDown API, along the lines of [this pull request](https://github.com/commonsguy/cwac-anddown/pull/8).

**Comment by sherry83062000** [comment]
玩出

**Comment by vickychijwani** [comment]
I suppose [all of these extension flags][flags] are within the scope of this issue? I'm particularly interested in `HOEDOWN_EXT_FENCED_CODE` at this point.

[flags]: https://github.com/commonsguy/cwac-anddown/blob/c497be6622ad408a2ca16c20d3b6aea4e45e451c/anddown/jni/src/document.h#L19-L39

**Comment by commonsguy** [comment]
@vickychijwani I haven't really looked at them in depth.

**Comment by commonsguy** [comment]
Addressed in v0.3.0.
